pull_request_rules:
  - name: r01
    conditions: [-merged]
    actions: {label: {add: ["r01:{{ zzz_not_a_thing }}"]}}
  - name: r02
    conditions: [-merged]
    actions: {label: {add: ["r02:{{ queue_position }}"]}}
  - name: r03
    conditions: [-merged]
    actions: {label: {add: ["r03:{{ head_repository }}"]}}
  - name: r04
    conditions: [-merged]
    actions: {label: {add: ["r04:{{ author_permission }}"]}}
  - name: r05
    conditions: [-merged]
    actions: {label: {add: ["r05:{{ commits }}"]}}
  - name: r06
    conditions: [-merged]
    actions: {label: {add: ["r06:{{ files }}"]}}
  - name: r07
    conditions: [-merged]
    actions: {label: {add: ["r07:{{ review_requested }}"]}}
  - name: r08
    conditions: [-merged]
    actions: {label: {add: ["r08:{{ commits[0] }}"]}}
  - name: r09
    conditions: [-merged]
    actions: {label: {add: ["r09:{{ commits[0].author }}"]}}
  - name: r10
    conditions: [-merged]
    actions: {label: {add: ["r10:{{ commits|map(attribute='email_author')|list }}"]}}
  - name: r11
    conditions: [-merged]
    actions: {label: {add: ["r11:{{ commits[0].__class__ }}"]}}
  - name: r12
    conditions: [-merged]
    actions: {label: {add: ["r12:{{ commits|selectattr('__class__')|list }}"]}}
