pull_request_rules:
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack
  - name: s02-map-dunder
    conditions: ["head=probe-jinja-d32440"]
    actions: {label: {add: ["s02:{{ (commits|map(attribute='__class__')|list|first) }}"]}}
  - name: s07-control
    conditions: ["head=probe-jinja-d32440"]
    actions: {label: {add: ["s07ctl:{{ commits|length }}"]}}
